# Generated by Django 6.0.6 on 2026-06-18 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("pipeline", "0002_etapa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Oportunidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de modificación"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="monto"),
                ),
                (
                    "fecha_cierre",
                    models.DateField(blank=True, null=True, verbose_name="fecha de cierre"),
                ),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oportunidades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asignado a",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oportunidades",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oportunidades",
                        to="pipeline.etapa",
                        verbose_name="etapa",
                    ),
                ),
            ],
            options={
                "verbose_name": "oportunidad",
                "verbose_name_plural": "oportunidades",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de modificación"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("llamada", "Llamada"),
                            ("email", "Email"),
                            ("reunion", "Reunión"),
                        ],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("nota", models.TextField(verbose_name="nota")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "oportunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="oportunidades.oportunidad",
                        verbose_name="oportunidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad",
                "verbose_name_plural": "actividades",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
