# Generated by Django 6.0.6 on 2026-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de modificación"),
                ),
                ("nombre", models.CharField(max_length=100, unique=True, verbose_name="nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripción")),
                ("es_default", models.BooleanField(default=False, verbose_name="es default")),
            ],
            options={
                "verbose_name": "pipeline",
                "verbose_name_plural": "pipelines",
                "ordering": ["nombre"],
            },
        ),
    ]
