# Generated by Django 6.0.6 on 2026-06-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de modificación"),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                ("orden", models.PositiveIntegerField(verbose_name="orden")),
                ("cerrada", models.BooleanField(default=False, verbose_name="cerrada")),
                ("es_ganado", models.BooleanField(default=False, verbose_name="es ganado")),
                (
                    "color",
                    models.CharField(blank=True, default="", max_length=7, verbose_name="color"),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="pipeline.pipeline",
                        verbose_name="pipeline",
                    ),
                ),
            ],
            options={
                "verbose_name": "etapa",
                "verbose_name_plural": "etapas",
                "ordering": ["pipeline", "orden"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pipeline", "orden"), name="unique_orden_per_pipeline"
                    )
                ],
            },
        ),
    ]
