# Generated by Django 6.0.6 on 2026-06-18 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusquedaGuardada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                ("endpoint", models.CharField(max_length=100, verbose_name="endpoint")),
                ("filtros", models.JSONField(default=dict, verbose_name="filtros")),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="busquedas_guardadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "búsqueda guardada",
                "verbose_name_plural": "búsquedas guardadas",
                "ordering": ["nombre"],
                "unique_together": {("endpoint", "nombre", "creado_por")},
            },
        ),
    ]
