# Generated by Django 6.0.6 on 2026-06-18 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        max_length=10,
                        verbose_name="action",
                    ),
                ),
                ("model", models.CharField(max_length=80, verbose_name="model")),
                ("object_id", models.PositiveBigIntegerField(verbose_name="object id")),
                ("object_repr", models.CharField(max_length=255, verbose_name="object repr")),
                ("changes", models.JSONField(default=dict, verbose_name="changes")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="timestamp")),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["model", "object_id"], name="audit_model_obj_idx"),
                    models.Index(fields=["timestamp"], name="audit_timestamp_idx"),
                ],
            },
        ),
    ]
