# Generated by Django 6.0.6 on 2026-06-18 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de modificación"),
                ),
                ("nombre", models.CharField(max_length=50, unique=True, verbose_name="nombre")),
                (
                    "color",
                    models.CharField(blank=True, default="", max_length=7, verbose_name="color"),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=200, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "etiqueta",
                "verbose_name_plural": "etiquetas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de modificación"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                ("nombre", models.CharField(max_length=150, verbose_name="nombre")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("telefono", models.CharField(blank=True, max_length=20, verbose_name="teléfono")),
                ("empresa", models.CharField(blank=True, max_length=150, verbose_name="empresa")),
                (
                    "ciudad",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="ciudad"
                    ),
                ),
                (
                    "pais",
                    models.CharField(blank=True, default="", max_length=80, verbose_name="país"),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="sitio web")),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "etiquetas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clientes",
                        to="clientes.etiqueta",
                        verbose_name="etiquetas",
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="fecha de modificación"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                ("nombre", models.CharField(max_length=150, verbose_name="nombre")),
                ("cargo", models.CharField(blank=True, max_length=100, verbose_name="cargo")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("telefono", models.CharField(blank=True, max_length=20, verbose_name="teléfono")),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "contacto",
                "verbose_name_plural": "contactos",
                "ordering": ["cliente", "nombre"],
            },
        ),
    ]
