# Generated by Django 6.0.6 on 2026-06-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="nombre")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("telefono", models.CharField(blank=True, max_length=20, verbose_name="teléfono")),
                ("empresa", models.CharField(blank=True, max_length=150, verbose_name="empresa")),
                (
                    "ciudad",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="ciudad"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="nombre")),
                ("cargo", models.CharField(blank=True, max_length=100, verbose_name="cargo")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("telefono", models.CharField(blank=True, max_length=20, verbose_name="teléfono")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="clientes.cliente",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "contacto",
                "verbose_name_plural": "contactos",
                "ordering": ["cliente", "nombre"],
            },
        ),
    ]
